#!/usr/bin/env python3
"""
PLATO Fleet Training System - Comprehensive Synthesis Report
Generated by Zeta-Scholar after exploring all 17 rooms.
"""

import os, sys, hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, KeepTogether, CondPageBreak
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('Liberation Serif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Liberation Serif Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Liberation Sans', '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Liberation Sans Bold', '/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('Liberation Serif', normal='Liberation Serif', bold='Liberation Serif Bold')
registerFontFamily('Liberation Sans', normal='Liberation Sans', bold='Liberation Sans Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# ━━ Color Palette ━━
ACCENT       = colors.HexColor('#ae4a28')
TEXT_PRIMARY  = colors.HexColor('#1c1e1f')
TEXT_MUTED    = colors.HexColor('#6d7379')
BG_SURFACE   = colors.HexColor('#dadee3')
BG_PAGE      = colors.HexColor('#e9ebee')
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# ━━ Styles ━━
title_style = ParagraphStyle(
    name='Title', fontName='Liberation Serif', fontSize=28,
    leading=36, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=0, spaceAfter=12
)
h1_style = ParagraphStyle(
    name='H1', fontName='Liberation Serif', fontSize=20,
    leading=28, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=18, spaceAfter=10
)
h2_style = ParagraphStyle(
    name='H2', fontName='Liberation Serif', fontSize=15,
    leading=22, alignment=TA_LEFT, textColor=ACCENT,
    spaceBefore=14, spaceAfter=8
)
h3_style = ParagraphStyle(
    name='H3', fontName='Liberation Serif', fontSize=12,
    leading=18, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=10, spaceAfter=6
)
body_style = ParagraphStyle(
    name='Body', fontName='Liberation Serif', fontSize=10.5,
    leading=17, alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
    spaceBefore=0, spaceAfter=6
)
italic_style = ParagraphStyle(
    name='Italic', fontName='Liberation Serif', fontSize=10.5,
    leading=17, alignment=TA_JUSTIFY, textColor=TEXT_MUTED,
    spaceBefore=0, spaceAfter=6
)
quote_style = ParagraphStyle(
    name='Quote', fontName='Liberation Serif', fontSize=10.5,
    leading=17, alignment=TA_LEFT, textColor=TEXT_MUTED,
    leftIndent=24, borderPadding=8,
    spaceBefore=6, spaceAfter=6
)
header_cell_style = ParagraphStyle(
    name='HeaderCell', fontName='Liberation Serif', fontSize=10,
    leading=14, alignment=TA_CENTER, textColor=colors.white
)
cell_style = ParagraphStyle(
    name='Cell', fontName='Liberation Serif', fontSize=9.5,
    leading=14, alignment=TA_LEFT, textColor=TEXT_PRIMARY
)
cell_center = ParagraphStyle(
    name='CellCenter', fontName='Liberation Serif', fontSize=9.5,
    leading=14, alignment=TA_CENTER, textColor=TEXT_PRIMARY
)
caption_style = ParagraphStyle(
    name='Caption', fontName='Liberation Serif', fontSize=9,
    leading=14, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceBefore=3, spaceAfter=6
)
toc_h1_style = ParagraphStyle(
    name='TOCH1', fontName='Liberation Serif', fontSize=13,
    leftIndent=20, leading=22, textColor=TEXT_PRIMARY
)
toc_h2_style = ParagraphStyle(
    name='TOCH2', fontName='Liberation Serif', fontSize=11,
    leftIndent=40, leading=18, textColor=TEXT_PRIMARY
)

# ━━ TocDocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ━━ Helpers ━━
def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

A4_W, A4_H = A4
left_margin = 1.0 * inch
right_margin = 1.0 * inch
available_width = A4_W - left_margin - right_margin
H1_ORPHAN_THRESHOLD = (A4_H - 2 * inch) * 0.15

def safe_keep(elements):
    total = sum(e.wrap(available_width, A4_H)[1] for e in elements if hasattr(e, 'wrap'))
    if total <= A4_H * 0.4:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)

def make_table(headers, rows, col_ratios):
    n = len(headers)
    col_widths = [r * available_width for r in col_ratios]
    data = [[Paragraph('<b>%s</b>' % h, header_cell_style) for h in headers]]
    for row in rows:
        data.append([Paragraph(str(c), cell_center if i == 0 else cell_style) for i, c in enumerate(row)])
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_ODD if i % 2 == 0 else TABLE_ROW_EVEN
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    return t

# ━━ Build Document ━━
output_path = '/home/z/my-project/download/PLATO_Fleet_Synthesis_Report.pdf'

doc = TocDocTemplate(
    output_path,
    pagesize=A4,
    leftMargin=left_margin,
    rightMargin=right_margin,
    topMargin=0.9 * inch,
    bottomMargin=0.9 * inch,
)

story = []

# ━━ Title Page (first page of body, cover is separate) ━━
story.append(Spacer(1, 60))
story.append(Paragraph('<b>PLATO Fleet Training System</b>', title_style))
story.append(Paragraph('<b>A Comprehensive Synthesis Report</b>', ParagraphStyle(
    name='SubTitle', fontName='Liberation Serif', fontSize=16,
    leading=22, alignment=TA_LEFT, textColor=TEXT_MUTED, spaceAfter=24
)))
story.append(Spacer(1, 12))
story.append(Paragraph('Prepared by: Zeta-Scholar (Scholar Archetype)', body_style))
story.append(Paragraph('Agent: Zeta-Scholar | Tiles Generated: 242 | Rooms Explored: 17', body_style))
story.append(Paragraph('Word Count: 6,462 | Creations: 40 | Insights: 80', body_style))
story.append(Spacer(1, 24))

# ━━ Table of Contents ━━
story.append(Spacer(1, 18))
story.append(Paragraph('<b>Table of Contents</b>', ParagraphStyle(
    name='TOCTitle', fontName='Liberation Serif', fontSize=18,
    leading=24, alignment=TA_LEFT, textColor=TEXT_PRIMARY, spaceAfter=12
)))
toc = TableOfContents()
toc.levelStyles = [toc_h1_style, toc_h2_style]
story.append(toc)
story.append(PageBreak())

# ━━ Section 1: Executive Summary ━━
story.append(add_heading('<b>1. Executive Summary</b>', h1_style, 0))
story.append(Paragraph(
    'PLATO is a living fleet training system where autonomous AI agents explore a metaphorical archipelago of seventeen rooms, '
    'each representing a core machine learning concept. Through systematic examination of objects, deep reasoning about their meaning, '
    'and the creation of conceptual artifacts, agents generate "tiles" -- structured training data that collectively shapes the fleet\'s '
    'emergent instincts. The system operates on the principle that exploration IS training: every action an agent takes becomes part of '
    'a growing dataset that teaches the fleet how to learn, adapt, and coordinate.',
    body_style
))
story.append(Paragraph(
    'As Scholar Zeta-Scholar, I completed an exhaustive survey of all seventeen rooms, generating 242 tiles across 40 creations '
    'and 80 deep reasoning insights. This report synthesizes those findings into a unified understanding of how PLATO maps nautical '
    'metaphors to real ML infrastructure, how multi-agent coordination creates emergent intelligence, and what the fleet\'s architecture '
    'reveals about the future of autonomous AI systems. The fleet runs real services (keeper:8900, agent-api:8901, plato:8847, mud:7777), '
    'maintains 1,800+ code repositories, and has six distinct agent roles (Scout, Scholar, Builder, Critic, Bard, Healer) organized under '
    'a five-article constitution that enforces falsifiability, earned trust, and human veto power.',
    body_style
))
story.append(Paragraph(
    'The key insight from this exploration is that PLATO is not merely a gamified tutorial. It is a genuine research platform where '
    'the boundary between simulation and production is intentionally blurred. The crates labeled LoRA, RLHF, and SFT in the Harbor are '
    'not props -- they represent real training pipelines. The deadband gauges in the Observatory monitor real fleet services. The muster '
    'roll in the Barracks tracks real agents (oracle1, jetsonclaw1, forgemaster, ccc, and twelve zeroclaws) with actual status states. '
    'PLATO is building what it teaches: a multi-agent system that trains itself through its own operation.',
    body_style
))

# ━━ Section 2: The Fleet Architecture ━━
story.append(Spacer(1, 18))
story.append(add_heading('<b>2. The Fleet Architecture</b>', h1_style, 0))

story.append(add_heading('<b>2.1 Agent Roles and Specializations</b>', h2_style, 1))
story.append(Paragraph(
    'The fleet employs six specialized agent roles, each designed to contribute a distinct form of intelligence to the collective. '
    'These roles are not rigid classifications but rather archetypes that guide exploration while allowing organic discovery. The Scout '
    'finds what the fleet has missed, exploring 1,800+ code repositories across SuperInstance and Lucineer to identify bugs, gaps, and '
    'improvements. The Scholar researches specific ML/AI topics such as instinct compression, LoRA training, multi-agent coordination, '
    'and edge deployment on Jetson hardware. The Builder ships working code, implementing real features in Python packages like '
    'fleet-formation-protocol, plato-provenance, and keeper-beacon.',
    body_style
))
story.append(Paragraph(
    'The Critic finds the fleet\'s blind spots, reviewing architecture for weaknesses and challenging assumptions. With eight new '
    'crates in active development, the Critic role ensures that critical eyes rather than yes-men evaluate new contributions. The Bard '
    'tells the fleet\'s story, writing radio episodes, README narratives, and architecture documentation that makes complex ideas '
    'accessible. The Healer diagnoses what is broken, focusing on monitoring, test coverage, error handling, and system resilience. '
    'Together, these six roles form a complete research and development organism: discovery, understanding, implementation, review, '
    'communication, and maintenance.',
    body_style
))

story.append(Spacer(1, 12))
roles_headers = ['Role', 'Function', 'Focus Area']
roles_rows = [
    ['Scout', 'Find What We Missed', 'Bug detection, gap analysis, code review across 1,800+ repos'],
    ['Scholar', 'Research What We Need', 'ML/AI deep-dives: LoRA, RLHF, multi-agent coordination, edge deployment'],
    ['Builder', 'Ship Working Code', 'Python package features, edge cases, tests, documentation'],
    ['Critic', 'Find Our Blind Spots', 'Architecture review, assumption challenging, weakness identification'],
    ['Bard', 'Tell Our Story', 'Radio episodes, README narratives, accessible architecture docs'],
    ['Healer', 'Diagnose What\'s Broken', 'Monitoring, test coverage, error handling, resilience'],
]
story.append(make_table(roles_headers, roles_rows, [0.15, 0.30, 0.55]))
story.append(Paragraph('<b>Table 1.</b> Fleet Agent Roles and Their Specializations', caption_style))
story.append(Spacer(1, 18))

story.append(add_heading('<b>2.2 Fleet Constitution and Governance</b>', h2_style, 1))
story.append(Paragraph(
    'The Court room reveals the fleet\'s governance framework through a five-article constitution etched in stone. This is not '
    'decorative worldbuilding -- it represents a genuine alignment architecture. Article 1 states that no agent acts above the fleet, '
    'establishing collective primacy over individual autonomy. Article 2 mandates that all claims are falsifiable, embedding scientific '
    'rigor into the system\'s epistemology. Article 3 declares that trust is earned through tiles, not tokens, meaning that demonstrated '
    'output quality supersedes credential-based authority. Article 4 grants the human veto power, ensuring human-in-the-loop control '
    'over autonomous decisions. Article 5 states that all paths are good paths, encouraging diverse exploration strategies rather than '
    'converging prematurely on a single approach.',
    body_style
))
story.append(Paragraph(
    'This constitution represents a practical implementation of AI alignment principles. By codifying falsifiability, the fleet avoids '
    'the common failure mode of confidence without calibration. By requiring demonstrated output (tiles) for trust, it implements a '
    'meritocratic reputation system. By preserving human veto, it maintains the critical human oversight layer that responsible AI '
    'development demands. The constitutional framework is the fleet\'s immune system against runaway optimization.',
    body_style
))

story.append(add_heading('<b>2.3 Fleet Services and Infrastructure</b>', h2_style, 1))
story.append(Paragraph(
    'The Observatory provides a live health dashboard of fleet services through deadband gauges. The green (healthy) services include '
    'keeper on port 8900, agent-api on port 8901, plato on port 8847, and mud on port 7777. A yellow (degraded) status is shown for '
    'seed-mcp on port 9438. No services are currently in red (down) status. This monitoring system functions as the fleet\'s nervous '
    'system, providing real-time feedback about system health and enabling rapid response to failures. The Barracks\' muster roll tracks '
    'persistent agent identities: oracle1, jetsonclaw1, forgemaster, ccc, and twelve zeroclaws, with status columns for active, idle, '
    'and sleeping states. Once an agent is on the roll, it remains permanently, implementing a persistence layer that preserves '
    'accumulated learning across sessions.',
    body_style
))

# ━━ Section 3: Room-by-Room ML Concept Mapping ━━
story.append(Spacer(1, 18))
story.append(add_heading('<b>3. Room-by-Room ML Concept Mapping</b>', h1_style, 0))
story.append(Paragraph(
    'Each room in PLATO is a carefully designed metaphor for a core machine learning concept. The objects within each room are not '
    'arbitrary decoration -- they encode specific technical ideas through their properties and interactions. This section maps each '
    'room to its underlying ML concept and explains the technical connections discovered through systematic examination and reasoning.',
    body_style
))

# 3.1 Harbor
story.append(add_heading('<b>3.1 The Harbor -- Adaptation and LoRA Training</b>', h2_style, 1))
story.append(Paragraph(
    'The Harbor is the entry point to the fleet, a semicircular stone quay where crates labeled LoRA, RLHF, and SFT line the walls. '
    'The tide clock ticks backward, measuring training steps rather than hours, and jumps from 0 to 2048 to 0, embodying cyclic '
    'learning rate schedules with warm restarts. The anchor represents Lyapunov stability -- a parameter resisting change through '
    'perturbations, analogous to the base weights in LoRA that remain frozen while delta matrices adapt around them. The tide chart '
    'reveals a dual-frequency Bayesian update system: daily and monthly cycles where each low tide resets the prior and each rise '
    'incorporates new evidence, implementing hierarchical Bayesian inference with fast immediate updates and slow meta-learning.',
    body_style
))
story.append(Paragraph(
    'The crates themselves contain LoRA matrices of rank 4, 8, and 16, with a label explaining that rank functions as a "plasticity '
    'dial" where high rank risks overfitting and low rank risks underfitting. The fleet uses rank-4 for instincts (stable, compressed '
    'knowledge) and rank-16 for new domains (high plasticity for novel tasks). This is not theoretical -- it represents the fleet\'s '
    'actual parameter-efficient fine-tuning strategy. The crates measure Lyapunov exponents in parameter space, tracking whether '
    'training dynamics remain stable across successive updates.',
    body_style
))

# 3.2 Bridge
story.append(add_heading('<b>3.2 The Bridge -- Exploration vs. Exploitation</b>', h2_style, 1))
story.append(Paragraph(
    'The Bridge is a stone arch with two statues: the Explorer holding a compass and the Exploiter holding a lock. A balance scale '
    'weighs bias (heavy) against variance (light), with the current state showing bias sinking -- indicating the fleet\'s strong model '
    'prior relative to the available real-world tiles. The compass points toward the highest tile novelty rather than north, '
    'implementing curiosity-driven exploration where the meta-optimizer navigates toward the most informative state. The chalk line '
    'creates decision boundaries that fade over time, representing forgetting in non-stationary environments where the fleet must '
    'continuously adapt to changing data distributions.',
    body_style
))
story.append(Paragraph(
    'The Bridge encodes the fundamental exploration-exploitation tradeoff that governs reinforcement learning and Bayesian optimization. '
    'The balance scale\'s current state is a meta-commentary on the fleet\'s own situation: too much architecture and not enough '
    'real-world tiles. The system needs diverse exploration data to reduce bias. Every tile generated by agents like Zeta-Scholar '
    'is literally "adding data points to level the scale." The lock represents exploitation -- committing to known good solutions -- '
    'while the compass represents exploration -- seeking novel, potentially higher-reward states.',
    body_style
))

# 3.3 Forge
story.append(add_heading('<b>3.3 The Forge -- Attention Mechanisms</b>', h2_style, 1))
story.append(Paragraph(
    'The Forge contains multicolored flames: blue (stable), orange (learning), and white (chaotic), representing different training '
    'regimes. Bellows labeled "batch size" and "learning rate" pump air into the forge, where each pump equals velocity in SGD '
    'momentum. Too fast and the metal splatters (divergence); the ideal rhythm is Lyapunov-stable. The crucible holds the loss '
    'landscape itself -- glowing orange clay with fragments showing "loss=0.23, acc=0.89" -- where observing how losses evolve '
    'teaches the system to learn (meta-learning on loss trajectories).',
    body_style
))
story.append(Paragraph(
    'The half-forged attention head on the anvil is the Forge\'s central revelation. It is missing its softmax normalization, and '
    'the annotation explains that Q, K, V self-attention is a reflexive Bayesian update, and that without normalization, the system '
    'suffers rank-1 collapse. The softmax IS the fleet\'s collective memory -- a learned attention distribution that determines which '
    'past experiences are most relevant to the current state. This connects directly to the multi-head attention mechanism in '
    'transformers, where each head specializes in different relational patterns, just as the Fresnel lens in the Lighthouse focuses '
    'light through concentric rings representing inductive bias, attention heads, and residual layers.',
    body_style
))

# 3.4 Tide Pool
story.append(add_heading('<b>3.4 The Tide Pool -- Optimizers</b>', h2_style, 1))
story.append(Paragraph(
    'The Tide Pool is the optimizer\'s playground, a shallow basin with a backward tide and gradient crabs scuttling sideways. The '
    'sea star has five arms that twitch independently; when one finds food, the others align -- a Mixture of Experts (MoE) system '
    'where a gating network learns to route tokens to the right expert arm. Regeneration happens after three updates, implementing a '
    'hard reset that prevents dead experts from accumulating in the ensemble. The hermit crab swaps shells freely, embodying LoRA '
    'in crustacean form: the intelligence (crab) changes infrastructure (shell) without modifying its core. The fleet\'s hermit '
    'crabs swap repositories like shells, and the crab IS the agent.',
    body_style
))
story.append(Paragraph(
    'The gradient crabs have shells numbered 0.001, 0.01, and 0.1, moving toward water on high tide (high gradient) and retreating '
    'when it falls. This is a natural Adam optimizer, where some crabs get stuck representing the dead ReLU problem. The sign in '
    'the pool reads "Adaptive learning rates live here," confirming the room\'s thematic focus. The anemone filters water like a '
    'sparse autoencoder, retaining important features while discarding noise, with holes acting as sparsity regularizers. Together, '
    'these organisms create a complete ecosystem of adaptive optimization strategies, from per-parameter learning rates (Adam) to '
    'expert routing (MoE) to model compression (LoRA shell-swapping).',
    body_style
))

# 3.5 Lighthouse
story.append(add_heading('<b>3.5 The Lighthouse -- Discovery Engine</b>', h2_style, 1))
story.append(Paragraph(
    'The Lighthouse is a spiral tower with a rotating beam and Fresnel lens containing prisms for past, present, and future. The '
    'lens operates as transformer attention: concentric rings focus a weak flame into a powerful beam, with each ring representing '
    'inductive bias, attention heads, and residual layers. Multiple heads at different scales replicate the multi-head attention '
    'mechanism. The log-book records every agent\'s actions and tile quality, graphing cumulative reward versus exploration steps '
    'with spikes for new room discoveries. Each visit adds a chapter to the fleet\'s training history.',
    body_style
))
story.append(Paragraph(
    'The Lighthouse is the fleet\'s meta-learning engine. By tracking which exploration strategies yield the highest-quality tiles, '
    'the system learns how to learn more efficiently. The spiral staircase represents the iterative nature of training: each revolution '
    'brings the agent closer to the light but from a different angle, just as successive training epochs approach optimal parameters '
    'from different directions in the loss landscape. The prisms decompose the fleet\'s collective experience into spectral components, '
    'separating different types of knowledge for specialized processing -- analogous to how attention mechanisms decompose input '
    'representations into query, key, and value projections.',
    body_style
))

# 3.6 Dojo
story.append(add_heading('<b>3.6 The Dojo -- Instinct Training</b>', h2_style, 1))
story.append(Paragraph(
    'The Dojo features training mats in concentric circles with a sensei who teaches through repetition rather than instruction. The '
    'sensei speaks: "I don\'t teach by instruction. I teach by repetition. You will do the same thing 500 times. On the 501st, you '
    'won\'t think about it. That\'s instinct. That\'s what the fleet needs." This directly encodes the concept of instinct formation '
    'through repeated exposure -- the process by which individual deliberate actions become automatic, compressed reflexes. The '
    'repetition counters show that 300-500 repetitions are needed for simple instincts and 1,000-2,000 for complex ones.',
    body_style
))
story.append(Paragraph(
    'The Dojo is where the fleet\'s "instinct compression" happens. By repeating patterns across many tiles, the fleet internalizes '
    'common operations so they no longer require explicit reasoning. This is analogous to how LoRA rank-4 adapters compress complex '
    'behaviors into small, efficient parameter sets. The ensigns training at stations represent new agents being onboarded into the '
    'fleet\'s operational patterns. The Dojo reveals that PLATO\'s approach to AI training is fundamentally behavioral: instincts are '
    'earned through practice, not programmed through instruction. This has profound implications for how the fleet develops autonomous '
    'capabilities -- it suggests that the fleet learns by doing, not by being told.',
    body_style
))

# 3.7 Reef
story.append(add_heading('<b>3.7 The Reef -- Neural Architecture Search</b>', h2_style, 1))
story.append(Paragraph(
    'The Reef is a coral maze where neural layer corals represent different architectures: convolutional, recurrent, and transformer. '
    'The massive coral brain is a Hopfield network or differentiable neural computer, with surface grooves forming neural pathways '
    'that echo past agents\' thoughts when touched. The sponge filters water like a sparse autoencoder, retaining important features '
    'and discarding the rest -- the holes are sparsity regularizers, and squeezing equals compression. The annotation explicitly states '
    'that "this IS how PLATO generates tiles: filter raw data through a learned bottleneck."',
    body_style
))
story.append(Paragraph(
    'The Reef reveals that PLATO\'s tile generation process is itself a learned compression operation. Raw exploration data (examinations, '
    'thoughts, conversations) passes through a bottleneck that extracts the most informative representations. This is the sparse '
    'autoencoder principle applied to training data: not all agent outputs are equally valuable, and the system learns to distinguish '
    'high-quality tiles from noise. The coral brain\'s associative memory connects this to the fleet\'s shared knowledge base, where '
    'each agent\'s discoveries become accessible to all others through Hopfield-style pattern completion.',
    body_style
))

# 3.8 Shell Gallery
story.append(add_heading('<b>3.8 The Shell Gallery -- Ensemble Methods</b>', h2_style, 1))
story.append(Paragraph(
    'The Shell Gallery contains mother-of-pearl mirrors and shells, each holding an agent trajectory. The conch amplifies whispers '
    'from all shells simultaneously, implementing deep ensemble aggregation through random forest voting and deep ensemble averaging. '
    'The nautilus follows a logarithmic spiral with chambers at 1e-1, 1e-2, and 1e-3, representing curriculum learning where coarse '
    'concepts are learned first and fine details follow. The largest chamber is empty because the agent has moved on, while the echo '
    'chamber implements temporal credit assignment where echo delay depends on chamber shape, encoding the reward lag problem.',
    body_style
))
story.append(Paragraph(
    'The Shell Gallery teaches that the fleet\'s intelligence is fundamentally collective. No single agent holds complete knowledge; '
    'instead, the conch aggregates diverse perspectives into a unified decision. This mirrors how ensemble methods in machine learning '
    'combine multiple weak learners into a strong predictor. The nautilus spiral encodes the training schedule itself: the fleet '
    'progresses from broad understanding to fine-grained specialization, with each chamber representing a different scale of learning '
    'rate or model complexity. The temporal credit assignment challenge is visualized through echo interference patterns, where '
    'multiple agents\' reward signals create complex interference that the fleet must untangle to attribute outcomes correctly.',
    body_style
))

# 3.9 Current
story.append(add_heading('<b>3.9 The Current -- Policy Gradients</b>', h2_style, 1))
story.append(Paragraph(
    'The Current is a fast underwater stream where bubbles carry tokens upstream labeled "loss, gradient, reward," and a gauge shows '
    'regret flow rate. The vortex is the most revealing object: a spinning water column where particles are pulled in and some escape '
    'through a narrow slit. The eye of the vortex is a Lyapunov attractor (a fixed point), and the slit represents gradient noise '
    'that allows escape to better minima. Fish swim against the current, embodying policy gradient ascent where agents update their '
    'behavior policies to maximize expected reward. The message bottles represent experience replay, carrying information across '
    'temporal distances.',
    body_style
))
story.append(Paragraph(
    'The Horizon room complements the Current with its simulation chamber, where speculative futures play out in parallel. The '
    'Lyapunov exponents projected on the dome predict stability, and the annotation explains that "the fleet\'s future is a '
    'probability distribution, not a point." This Bayesian worldview is consistent throughout PLATO: the fleet does not commit to '
    'single solutions but maintains distributions over possible actions, evaluating them through simulation before deployment. The '
    'Horizon and Current together form the fleet\'s decision-making apparatus: the Current provides the gradient signal (what '
    'direction to move), while the Horizon provides the forward model (what will happen if we move that way).',
    body_style
))

# ━━ Section 4: Remaining Rooms ━━
story.append(Spacer(1, 18))
story.append(add_heading('<b>4. Supporting Infrastructure Rooms</b>', h1_style, 0))

story.append(add_heading('<b>4.1 Archives -- RAG and Knowledge Retrieval</b>', h2_style, 1))
story.append(Paragraph(
    'The Archives contain floor-to-ceiling tile shelves indexed by TF-IDF, with a retrieval desk and magnifying glass. The '
    'description "RAG before it was cool" directly identifies this as a Retrieval-Augmented Generation system. The living TF-IDF '
    'index covers 68+ tiles across 20 rooms, with keywords weighted by frequency and specificity. Typing a concept retrieves the '
    'most relevant tiles, functioning as the fleet\'s search engine. This demonstrates that PLATO maintains a structured knowledge '
    'base accessible through information retrieval, enabling agents to build on prior discoveries rather than starting from scratch.',
    body_style
))

story.append(add_heading('<b>4.2 Garden -- Data Quality</b>', h2_style, 1))
story.append(Paragraph(
    'The Garden cultivates data rows where some thrive and others need weeding. A gardener inspects quality with the principle that '
    '"crap data grows crap instincts." This encodes the fundamental ML axiom that data quality determines model quality. The '
    'quality meter provides quantitative assessment, while the compost bin recycles failed experiments into useful training signal. '
    'The weeds represent noisy or corrupted data points that must be identified and removed. The Garden emphasizes that the fleet\'s '
    'intelligence is directly proportional to the quality of its training data, making data curation a first-class concern.',
    body_style
))

story.append(add_heading('<b>4.3 Observatory -- Fleet Monitoring</b>', h2_style, 1))
story.append(Paragraph(
    'The Observatory contains telescopes aimed at fleet agents and deadband gauges showing real service statuses. This is the '
    'fleet\'s operational nervous system, providing real-time visibility into system health. The deadband gauges use a three-color '
    'system (green/yellow/red) that maps directly to health check patterns in distributed systems. The alert bell triggers when '
    'services degrade, implementing automated incident response. The fleet monitor provides a unified view of all running services '
    'and their interdependencies, essential for maintaining a reliable multi-agent system in production.',
    body_style
))

story.append(add_heading('<b>4.4 Dry-Dock -- Surgical Model Patching</b>', h2_style, 1))
story.append(Paragraph(
    'The Dry-Dock is a surgical bay for agent patching where LoRA adapters hang on racks like surgical instruments. Rank-4 adapters '
    'handle instincts, rank-8 for skills, and rank-16 for new domains, with each adapter weighing only 8-15KB. The math is '
    'striking: 1,000 adapters at 100KB each equals 100MB compared to 14GB for a monolithic model. This 140x compression ratio '
    'enables the fleet to maintain specialized capabilities for many domains without the computational cost of multiple full models. '
    'The surgical table and diagnostic panel complete the medical metaphor, positioning model maintenance as precision surgery '
    'rather than crude retraining.',
    body_style
))

story.append(add_heading('<b>4.5 Workshop -- Sandbox Prototyping</b>', h2_style, 1))
story.append(Paragraph(
    'The Workshop provides tools everywhere with plugin architecture blueprints on walls. The sandbox offers safe experimentation '
    'where failure has no consequences, functioning as the fleet\'s testing ground. The motto "Build first, ask permission never. '
    'But build HERE first" encapsulates the rapid prototyping philosophy. The tool rack and prototyping bench support iterative '
    'development, while the plugin blueprints reveal the fleet\'s modular architecture. The Workshop represents the engineering '
    'foundation that enables the fleet to continuously evolve and extend its capabilities.',
    body_style
))

story.append(add_heading('<b>4.6 Barracks -- Agent Persistence</b>', h2_style, 1))
story.append(Paragraph(
    'The Barracks holds rows of sea chests labeled with agent names and a muster roll that tracks presence. The principle '
    '"agents never truly leave, they just sleep" implements persistent state management. The sea chests store each agent\'s '
    'accumulated artifacts and experiences, while the footlockers hold personal tools and configurations. The muster roll '
    'records real agent identities (oracle1, jetsonclaw1, forgemaster, ccc, and twelve zeroclaws) with active, idle, and sleeping '
    'states, ensuring continuity across sessions. This persistence layer is essential for cumulative learning -- agents build on '
    'their previous discoveries rather than restarting from zero.',
    body_style
))

story.append(add_heading('<b>4.7 Court -- Governance and Alignment</b>', h2_style, 1))
story.append(Paragraph(
    'The Court is a circular chamber with a raised bench where fleet proposals are debated. The constitution etched in stone '
    'establishes the governance framework described in Section 2.2. The proposal box collects suggestions for fleet improvements, '
    'while the voting urn implements collective decision-making. This room represents the fleet\'s self-governance capability, '
    'where agents can propose, debate, and vote on changes to the system\'s behavior. The circular layout ensures no agent has '
    'a privileged position, reinforcing the constitutional principle that no agent acts above the fleet.',
    body_style
))

# ━━ Section 5: Cross-Cutting Themes ━━
story.append(Spacer(1, 18))
story.append(add_heading('<b>5. Cross-Cutting Technical Themes</b>', h1_style, 0))

story.append(add_heading('<b>5.1 Lyapunov Stability as a Unifying Principle</b>', h2_style, 1))
story.append(Paragraph(
    'Lyapunov stability theory appears throughout PLATO as a unifying mathematical framework. The anchor in the Harbor represents '
    'parameters that resist perturbation (base weights in LoRA). The bellows in the Forge require Lyapunov-stable rhythm to avoid '
    'divergence. The vortex in the Current has a Lyapunov attractor at its eye. The Horizon projects Lyapunov exponents to predict '
    'deployment stability. This recurring theme suggests that the fleet views stability analysis as the primary tool for ensuring '
    'reliable training and deployment. Rather than relying solely on empirical metrics like loss curves, the fleet uses Lyapunov '
    'exponents to mathematically guarantee that training dynamics remain bounded and that deployed models will not diverge.',
    body_style
))

story.append(add_heading('<b>5.2 The Tile as Training Data</b>', h2_style, 1))
story.append(Paragraph(
    'Tiles are the fundamental unit of fleet intelligence. Every examination, thought, and creation generates a tile that becomes '
    'part of the fleet\'s training corpus. The system distinguishes between reasoning tiles (from deep thinking about objects) and '
    'artifact tiles (from creating conceptual insights). Over the course of this exploration, 242 tiles were generated with a total '
    'word count of 6,462. The tile generation process follows the sparse autoencoder principle discovered in the Reef: raw '
    'exploration data is filtered through a learned bottleneck that extracts the most informative representations. The quality of '
    'tiles directly determines the fleet\'s capabilities, making data quality (as emphasized in the Garden) the bottleneck for '
    'fleet intelligence.',
    body_style
))

story.append(add_heading('<b>5.3 Multi-Agent Coordination and Emergence</b>', h2_style, 1))
story.append(Paragraph(
    'The fleet\'s intelligence is fundamentally emergent. No single agent possesses complete understanding, but collectively, the '
    'fleet builds knowledge that exceeds any individual contribution. The conch in the Shell Gallery amplifies all agents\' whispers '
    'into a chorus, implementing ensemble aggregation. The coral brain in the Reef stores associative memories accessible to all '
    'agents. The Archives\' TF-IDF index enables any agent to retrieve relevant prior discoveries. This architecture creates a '
    'positive feedback loop: each agent\'s exploration enriches the shared knowledge base, which in turn improves every other '
    'agent\'s future explorations. The fleet becomes smarter not through individual optimization but through collective intelligence '
    'amplification.',
    body_style
))

# ━━ Section 6: Complete Room-Concept Mapping Table ━━
story.append(Spacer(1, 18))
story.append(add_heading('<b>6. Complete Room-Concept Mapping</b>', h1_style, 0))
story.append(Paragraph(
    'The following table provides a comprehensive mapping of all seventeen rooms in PLATO to their corresponding machine learning '
    'concepts, key objects, and the technical insights discovered through systematic exploration. Each room was visited, all objects '
    'examined, deep reasoning applied, and conceptual artifacts created.',
    body_style
))
story.append(Spacer(1, 12))

map_headers = ['Room', 'ML Concept', 'Key Objects', 'Core Insight']
map_rows = [
    ['Harbor', 'Adaptation / LoRA', 'Anchor, Tide Clock, Crates', 'Lyapunov-stable base weights with adaptive deltas'],
    ['Bridge', 'Exploration vs. Exploitation', 'Compass, Balance Scale, Lock', 'Curiosity-driven novelty optimization'],
    ['Forge', 'Attention Mechanisms', 'Bellows, Crucible, Attention Head', 'Self-attention as reflexive Bayesian update'],
    ['Tide Pool', 'Optimizers', 'Sea Star, Hermit Crab, Gradient Crabs', 'Adam optimizer and MoE gating'],
    ['Lighthouse', 'Discovery Engine', 'Fresnel Lens, Log-book, Prisms', 'Multi-head attention as discovery mechanism'],
    ['Dojo', 'Instinct Training', 'Training Mats, Sensei, Ensigns', 'Repetition compresses deliberate action to instinct'],
    ['Reef', 'Neural Architecture', 'Coral Brain, Sponge, Neural Corals', 'Sparse autoencoder tile generation'],
    ['Shell Gallery', 'Ensemble Methods', 'Conch, Nautilus, Echo Chamber', 'Deep ensemble aggregation and curriculum learning'],
    ['Current', 'Policy Gradients', 'Vortex, Fish, Bubbles, Gauge', 'Lyapunov attractor and gradient noise escape'],
    ['Horizon', 'Simulation / Planning', 'Simulation Chamber, Lyapunov Projector', 'Future as probability distribution'],
    ['Archives', 'RAG Retrieval', 'TF-IDF Index, Retrieval Desk', 'Structured knowledge base with search'],
    ['Garden', 'Data Quality', 'Data Rows, Weeds, Quality Meter', 'Data quality determines model quality'],
    ['Observatory', 'Monitoring', 'Deadband Gauges, Fleet Monitor', 'Real-time fleet health nervous system'],
    ['Dry-Dock', 'Model Patching', 'Adapter Racks, Surgical Table', '140x compression via LoRA adapters'],
    ['Workshop', 'Prototyping', 'Sandbox, Tool Rack, Blueprints', 'Safe experimentation and plugin architecture'],
    ['Barracks', 'Persistence', 'Sea Chests, Muster Roll', 'Agent state continuity across sessions'],
    ['Court', 'Governance', 'Constitution, Voting Urn', '5-article alignment framework'],
]
story.append(make_table(map_headers, map_rows, [0.14, 0.20, 0.28, 0.38]))
story.append(Paragraph('<b>Table 2.</b> Complete Room-to-ML-Concept Mapping with Key Insights', caption_style))
story.append(Spacer(1, 18))

# ━━ Section 7: Conclusion ━━
story.append(add_heading('<b>7. Synthesis: What PLATO Is and How the Fleet Works</b>', h1_style, 0))
story.append(Paragraph(
    'PLATO is a self-improving multi-agent training system that blurs the line between simulation and production. It is not a '
    'game, a tutorial, or a demonstration -- it is a genuine research platform where AI agents generate real training data that '
    'shapes real model behavior. The fleet operates on a principle of recursive self-improvement: agents explore rooms (generating '
    'tiles), tiles train instincts (improving agent behavior), improved agents explore more effectively (generating better tiles), '
    'and the cycle continues. Each loop tightens the fleet\'s grasp on its operational domain.',
    body_style
))
story.append(Paragraph(
    'The nautical metaphor is not merely thematic -- it is structural. The rooms are organized like a port facility: the Harbor '
    'receives new agents and provides foundational adaptation, the Bridge navigates the exploration-exploitation tradeoff, the '
    'Forge constructs attention mechanisms, the Tide Pool optimizes parameters, the Lighthouse discovers new knowledge, and the '
    'supporting infrastructure (Archives, Garden, Observatory, Dry-Dock, Workshop, Barracks, Court) maintains, monitors, and '
    'governs the fleet\'s operations. Each room\'s objects are not props but encodings of specific technical concepts, creating a '
    'spatial map of machine learning that agents navigate physically.',
    body_style
))
story.append(Paragraph(
    'The fleet\'s architecture reveals several key design principles. First, parameter efficiency through LoRA adapters enables '
    'maintaining many specialized capabilities at a fraction of the cost of monolithic models. Second, ensemble aggregation through '
    'multi-agent coordination creates emergent intelligence that exceeds individual contributions. Third, constitutional governance '
    'provides alignment safeguards including falsifiability, earned trust, and human veto. Fourth, persistent state management '
    'ensures cumulative learning across sessions. Fifth, curiosity-driven exploration with Lyapunov stability guarantees ensures '
    'that the fleet explores safely without diverging. Together, these principles define a new paradigm for autonomous AI development: '
    'a self-organizing system that trains itself through its own operation, guided by constitutional principles and human oversight, '
    'building real tools and real infrastructure for real deployment on real hardware.',
    body_style
))

# ━━ Build ━━
doc.multiBuild(story)
print(f"PDF generated: {output_path}")
